// This file is automatically generated.

interface CssExports {
  'container': string;
  'container--fixed': string;
  'containerFixed': string;
}

declare var cssExports: CssExports;
export = cssExports;
