// This file is automatically generated.

interface CssExports {
  'layout': string;
  'layout-content': string;
  'layout-route-content': string;
  'layoutContent': string;
  'layoutRouteContent': string;
}

declare var cssExports: CssExports;
export = cssExports;
