// This file is automatically generated.

interface CssExports {
  'header-menu--lg': string;
  'header-menu--sm': string;
  'headerMenuLg': string;
  'headerMenuSm': string;
}

declare var cssExports: CssExports;
export = cssExports;
