// This file is automatically generated.

interface CssExports {
  'button': string;
  'container': string;
  'hospital': string;
  'icon': string;
  'icon0': string;
  'icon1': string;
  'icon2': string;
  'icon3': string;
  'icon4': string;
  'section': string;
  'section--fixed': string;
  'sectionFixed': string;
  'selection': string;
  'selection--selected': string;
  'selectionSelected': string;
}

declare var cssExports: CssExports;
export = cssExports;
