// This file is automatically generated.

interface CssExports {
  'button': string;
  'group': string;
  'icon': string;
  'icon-container': string;
  'icon0': string;
  'icon1': string;
  'icon2': string;
  'icon3': string;
  'icon4': string;
  'iconContainer': string;
}

declare var cssExports: CssExports;
export = cssExports;
