// This file is automatically generated.

interface CssExports {
  'logo': string;
  'logoIcon': string;
  'logoText': string;
  'logo__icon': string;
  'logo__text': string;
}

declare var cssExports: CssExports;
export = cssExports;
